import React from 'react';
import { Search, Sparkles, Globe } from 'lucide-react';

const TabSEO = ({ formData, updateField }) => {
  const seo = formData.seo || {
    seoTitle: '',
    metaDescription: '',
    focusKeyword: '',
    canonicalUrl: '',
    ogTitle: '',
    ogDescription: ''
  };

  const updateSEO = (key, value) => {
    updateField('seo', { ...seo, [key]: value });
  };

  const autoGenerateDefaults = () => {
    const name = formData.name || 'Agricultural Machinery';
    const brand = formData.brand || 'AgriMachina';
    const cat = formData.category || 'Farm Equipment';

    updateField('seo', {
      ...seo,
      seoTitle: `${name} - ${brand} | Buy Online at Best Price in India`,
      metaDescription: `Buy high performance ${name} by ${brand} (${cat}). 100% genuine OEM warranty, doorstep pan-India delivery, and easy monthly Kisan EMI options.`,
      focusKeyword: `${name} ${brand}`.toLowerCase(),
      canonicalUrl: `https://agrimachina.in/product/${formData.slug || 'item'}`
    });
  };

  const previewTitle = seo.seoTitle || `${formData.name || 'Product Title'} | AgriMachina India`;
  const previewDesc = seo.metaDescription || formData.shortDescription || 'Buy high performance agricultural machinery online with verified warranty and easy EMI options.';
  const previewSlug = formData.slug || 'power-weeder-7hp';

  return (
    <div className="flex flex-col gap-6">
      {/* Auto-generate button */}
      <div className="flex justify-between items-center" style={{ background: '#070d1a', border: '1px solid #1e2e4f', borderRadius: '12px', padding: '1rem' }}>
        <div>
          <div style={{ fontWeight: 700, color: '#ffffff', fontSize: '0.95rem' }}>
            Smart SEO Metadata Auto-Generation
          </div>
          <div style={{ fontSize: '0.8rem', color: '#94a3b8' }}>
            Generates optimized Google meta titles and descriptions automatically from product specs.
          </div>
        </div>
        <button type="button" onClick={autoGenerateDefaults} className="btn btn-accent btn-sm">
          <Sparkles size={15} />
          <span>Auto-Generate Defaults</span>
        </button>
      </div>

      {/* Google Search Live Preview Card */}
      <div style={{ background: '#ffffff', borderRadius: '12px', padding: '1.25rem', border: '1px solid #e2e8f0', color: '#1e293b' }}>
        <div style={{ fontSize: '0.75rem', fontWeight: 700, color: '#64748b', textTransform: 'uppercase', marginBottom: '0.5rem', display: 'flex', alignItems: 'center', gap: '0.35rem' }}>
          <Globe size={14} color="#166534" />
          <span>Google Search SERP Preview</span>
        </div>

        <div style={{ fontSize: '0.8rem', color: '#202124', marginBottom: '2px', wordBreak: 'break-all' }}>
          https://agrimachina.in › product › <strong style={{ color: '#006621' }}>{previewSlug}</strong>
        </div>
        <div style={{ fontSize: '1.15rem', color: '#1a0dab', fontWeight: 600, lineHeight: 1.3, marginBottom: '4px', cursor: 'pointer' }}>
          {previewTitle}
        </div>
        <div style={{ fontSize: '0.85rem', color: '#4d5156', lineHeight: 1.45 }}>
          {previewDesc}
        </div>
      </div>

      {/* Inputs Grid */}
      <div className="flex flex-col gap-4">
        <div className="input-group">
          <label className="input-label" style={{ color: '#cbd5e1' }}>SEO Meta Title (Recommended 50-60 characters)</label>
          <input
            type="text"
            className="input-field"
            style={{ background: '#0b1324', borderColor: '#1e2e4f', color: '#ffffff' }}
            value={seo.seoTitle || ''}
            onChange={(e) => updateSEO('seoTitle', e.target.value)}
            placeholder="e.g. Power Weeder 7HP Petrol 4-Stroke | AgriPro Master"
          />
        </div>

        <div className="input-group">
          <label className="input-label" style={{ color: '#cbd5e1' }}>Meta Description (Recommended 140-160 characters)</label>
          <textarea
            className="textarea-field"
            rows="3"
            style={{ background: '#0b1324', borderColor: '#1e2e4f', color: '#ffffff' }}
            value={seo.metaDescription || ''}
            onChange={(e) => updateSEO('metaDescription', e.target.value)}
            placeholder="Meta summary shown in search engine results snippets..."
          />
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div className="input-group">
            <label className="input-label" style={{ color: '#cbd5e1' }}>Focus Target Keyword</label>
            <input
              type="text"
              className="input-field"
              style={{ background: '#0b1324', borderColor: '#1e2e4f', color: '#ffffff' }}
              value={seo.focusKeyword || ''}
              onChange={(e) => updateSEO('focusKeyword', e.target.value)}
              placeholder="e.g. power weeder 7hp petrol"
            />
          </div>

          <div className="input-group">
            <label className="input-label" style={{ color: '#cbd5e1' }}>Canonical URL</label>
            <input
              type="text"
              className="input-field"
              style={{ background: '#0b1324', borderColor: '#1e2e4f', color: '#ffffff' }}
              value={seo.canonicalUrl || ''}
              onChange={(e) => updateSEO('canonicalUrl', e.target.value)}
              placeholder="https://agrimachina.in/product/..."
            />
          </div>
        </div>
      </div>
    </div>
  );
};

export default TabSEO;
