import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const LANGUAGES = [
  { code: 'en', label: 'English', native: 'English', flag: '🇬🇧' },
  { code: 'hi', label: 'Hindi', native: 'हिन्दी', flag: '🇮🇳' },
  { code: 'gu', label: 'Gujarati', native: 'ગુજરાતી', flag: '🌾' },
  { code: 'pa', label: 'Punjabi', native: 'ਪੰਜਾਬੀ', flag: '🚜' },
  { code: 'mr', label: 'Marathi', native: 'मराठी', flag: '🇮🇳' },
  { code: 'te', label: 'Telugu', native: 'తెలుగు', flag: '🇮🇳' }
];

const phraseDictionary = {
  // Common Machinery Titles
  'Heavy-Duty 6-Foot Rotavator (Multi-Speed)': {
    hi: 'हेवी-ड्यूटी 6-फुट रोटावेटर (मल्टी-स्पीड गियरबॉक्स)',
    gu: 'હેવી-ડ્યુટી 6-ફૂટ રોટાવેટર (મલ્ટી-સ્પીડ ગિયરબોક્સ)',
    pa: 'ਹੈਵੀ-ਡਿਊਟੀ 6-ਫੁੱਟ ਰੋਟਾਵੇਟਰ (ਮਲਟੀ-ਸਪੀਡ ਗਿਅਰਬਾਕਸ)',
    mr: 'हेवी-ड्युटी 6-फूट रोटाव्हेटर (मल्टी-स्पीड गिअरबॉक्स)',
    te: 'హెవీ-డ్యూటీ 6-అడుగుల రోటావschedule (మల్టీ-స్పీడ్ గేర్‌బాక్స్)'
  },
  'Power Weeder 7HP Petrol 4-Stroke (AV-708)': {
    hi: 'पावर वीडर 7HP पेट्रोल 4-स्ट्रोक (AV-708)',
    gu: 'પાવર વીડર 7HP પેટ્રોલ 4-સ્ટ્રોક (AV-708)',
    pa: 'ਪਾਵਰ ਵੀਡਰ 7HP ਪੈਟਰੋਲ 4-ਸਟ੍ਰੋਕ (AV-708)',
    mr: 'पॉवर विडर 7HP पेट्रोल 4-स्ट्रोक (AV-708)',
    te: 'పవర్ వీడర్ 7HP పెట్రోల్ 4-స్ట్రోక్ (AV-708)'
  },
  '5HP Solar Submersible Pump Set (DC Brushless)': {
    hi: '5HP सोलर सबमर्सिबल पंप सेट (डीसी ब्रशलेस)',
    gu: '5HP સોલર સબમર્સિબલ પંપ સેટ (ડીસી બ્રશલેસ)',
    pa: '5HP ਸੋਲਰ ਸਬਮਰਸੀਬਲ ਪੰਪ ਸੈੱਟ (ਡੀਸੀ ਬ੍ਰਸ਼ਲੈੱਸ)',
    mr: '5HP सोलर सबमर्सिबल पंप संच (डीसी ब्रशलेस)',
    te: '5HP సోలార్ సబ్‌మెర్సిబుల్ పంప్ సెట్ (డిసి బ్రష్‌లెస్‌)'
  },
  '50cc Backpack Multi-Crop Brush Cutter & Harvester': {
    hi: '50cc बैकपैक मल्टी-क्रॉप ब्रश कटर व हार्वेस्टर',
    gu: '50cc બેકપેક મલ્ટી-ક્રોપ બ્રશ કટર અને હાર્વેસ્ટર',
    pa: '50cc ਬੈਕਪੈਕ ਮਲਟੀ-ਕ੍ਰੌਪ ਬ੍ਰਸ਼ ਕਟਰ ਅਤੇ ਹਾਰਵੈਸਟਰ',
    mr: '50cc बॅकपॅक मल्टी-क्रॉप ब्रश कटर व हार्वेस्टर',
    te: '50cc బ్యాక్‌ప్యాక్ మల్టీ-క్రాప్ బ్రష్ కట్టర్ & హార్వెస్టర్'
  },
  '2-in-1 Battery cum Manual Sprayer (16L)': {
    hi: '2-इन-1 बैटरी व मैन्युअल स्प्रेयर (16 लीटर)',
    gu: '2-ઇન-1 બેટરી અને મેન્યુઅલ સ્પ્રેયર (16 લિટર)',
    pa: '2-ਇਨ-1 ਬੈਟਰੀ ਤੇ ਮੈਨੂਅਲ ਸਪ੍ਰੇਅਰ (16 ਲੀਟਰ)',
    mr: '2-इन-1 बॅटरी व मॅन्युअल स्प्रेअर (16 लिटर)',
    te: '2-ఇన్-1 బ్యాటరీ & మాన్యువల్ స్ప్రేయర్ (16 లీటర్లు)'
  },

  // Descriptions
  'Dual-speed heavy tractor rotavator for single-pass seedbed preparation in wet puddle and hard dry soil.': {
    hi: 'गीले कीचड़ और कठोर सूखी मिट्टी में एक ही बार में उत्तम बीज क्यारी तैयार करने के लिए दोहरे-स्पीड वाला हेवी ट्रैक्टर रोटावेटर।',
    gu: 'ભીની અને સખત સૂકી જમીનમાં એક જ ફેરામાં ઉત્તમ જમીન તૈયાર કરવા માટે ડ્યુઅલ-સ્પીડ હેવી ટ્રેક્ટર રોટાવેટર.',
    pa: 'ਗਿੱਲੀ ਅਤੇ ਸਖ਼ਤ ਸੁੱਕੀ ਜ਼ਮੀਨ ਵਿੱਚ ਇੱਕੋ ਗੇੜੇ ਵਿੱਚ ਬੀਜ ਬਿਜਾਈ ਲਈ ਵਧੀਆ ਤਿਆਰੀ ਕਰਨ ਵਾਲਾ ਡੁਅਲ-ਸਪੀਡ ਹੈਵੀ ਟਰੈਕਟਰ ਰੋਟਾਵੇਟਰ।',
    mr: 'ओल्या चिखलात आणि कठीण कोरड्या जमिनीत एकाच फेरीत उत्तम पेरणीयोग्य जमीन तयार करण्यासाठी ड्युअल-स्पीड हेवी ट्रॅक्टर रोटाव्हेटर.',
    te: 'తడి మరియు గట్టి పొడి నేలలో ఒకేసారి సరైన విత్తన మడిని సిద్ధం చేయడానికి డ్యూయల్-స్పీడ్ హెవీ ట్రాక్టర్ రోటావschedule.'
  },
  'High-torque 208cc power weeder engineered for deep inter-row soil cultivation across tough clay, cotton, and sugarcane fields.': {
    hi: 'कपास, गन्ना और सब्जियों के खेतों में गहरी निराई-गुड़ाई और जुताई के लिए 208cc का उच्च-टॉर्क पावर वीडर।',
    gu: 'કપાસ, શેરડી અને શાકભાજીના ખેતરોમાં ઊંડા નિંદામણ અને ખેડાણ માટે 208cc ઉચ્ચ-ટોર્ક પાવર વીડર.',
    pa: 'ਨਰਮਾ, ਕਮਾਦ ਅਤੇ ਸਬਜ਼ੀਆਂ ਦੇ ਖੇਤਾਂ ਵਿੱਚ ਡੂੰਘੀ ਗੋਡੀ ਤੇ ਵਹਾਈ ਲਈ 208cc ਹਾਈ-ਟਾਰਕ ਪਾਵਰ ਵੀਡਰ।',
    mr: 'कापूस, ऊस आणि भाजीपाल्याच्या शेतात खोल खुरपणी व मशागतीसाठी 208cc चा हाय-टॉर्क पॉवर विडर.',
    te: 'పత్తి, చెరకు మరియు కూరగాయల పొలాలలో లోతైన దుక్కి మరియు కలుపు తీయడానికి 208cc హై-టార్క్ పవర్ వీడర్.'
  },
  'Heavy-duty stainless steel solar pump set with smart MPPT controller for reliable, uninterrupted farm canal and borewell irrigation.': {
    hi: 'खेतों, नहरों और गहरे बोरवेल से बिना बिजली बिल के लगातार सिंचाई के लिए स्मार्ट MPPT कंट्रोलर युक्त स्टेनलेस स्टील सोलर पंप।',
    gu: 'બોરવેલ અને નહેરોમાંથી અવિરત સિંચાઈ માટે સ્માર્ટ MPPT કંટ્રોલર સાથે સ્ટેનલેસ સ્ટીલ સોલર પંપ સેટ.',
    pa: 'ਬਿਨਾਂ ਬਿਜਲੀ ਖਰਚੇ ਬੋਰਵੈੱਲ ਅਤੇ ਨਹਿਰੀ ਪਾਣੀ ਦੀ ਲਗਾਤਾਰ ਸਿੰਚਾਈ ਲਈ ਸਮਾਰਟ MPPT ਕੰਟਰੋਲਰ ਵਾਲਾ ਸੋਲਰ ਪੰਪ।',
    mr: 'विहिरी आणि कूपनलिकांमधून अखंड सिंचनासाठी स्मार्ट MPPT कंट्रोलरसह स्टेनलेस स्टील सोलर पंप संच.',
    te: 'కరెంట్ బిల్లు లేకుండా నిరంతర వ్యవసాయ సాగునీటి కోసం స్మార్ట్ MPPT కంట్రోలర్‌తో కూడిన సోలార్ పంప్ సెట్.'
  },
  'Harvest paddy, wheat, sugarcane, fodder grass, and dense thicket shrubs effortlessly with multi-blade attachments.': {
    hi: 'धान, गेहूं, गन्ना, चारा और झाड़ियों की तेजी से कटाई के लिए मल्टी-ब्लेड अटैचमेंट युक्त शक्तिशाली बैकपैक कटर।',
    gu: 'ડાંગર, ઘઉં, શેરડી અને ઘાસચારાની સરળતાથી કાપણી માટે મલ્ટી-બ્લેડ સાથેનું શક્તિશાળી કટર.',
    pa: 'ਝੋਨਾ, ਕਣਕ, ਕਮਾਦ ਅਤੇ ਪੱਠਿਆਂ ਦੀ ਤੇਜ਼ ਕਟਾਈ ਲਈ ਮਲਟੀ-ਬਲੇਡ ਅਟੈਚਮੈਂਟ ਵਾਲਾ ਕਟਰ।',
    mr: 'भात, गहू, ऊस आणि चाऱ्याची जलद कापणी करण्यासाठी विविध पात्यांसह शक्तिशाली कटर.',
    te: 'వరి, గోధుమలు, చెరకు మరియు పశుగ్రాసాన్ని సులభంగా కోయడానికి మల్టీ-బ్లేడ్ కట్టర్.'
  },

  // Specs & Highlights
  '48 Boron Steel L-Type Blades': {
    hi: '48 बोरॉन स्टील एल-टाइप ब्लेड्स',
    gu: '48 બોરોન સ્ટીલ એલ-ટાઈપ બ્લેડ્સ',
    pa: '48 ਬੋਰਾਨ ਸਟੀਲ ਐੱਲ-ਟਾਈਪ ਬਲੇਡ',
    mr: '48 बोरॉन स्टील एल-प्रकार पाते',
    te: '48 బోరాన్ స్టీల్ L-రకం బ్లేడ్లు'
  },
  'Multi-Speed Heavy Cast Iron Gearbox': {
    hi: 'मल्टी-स्पीड हेवी कास्ट आयरन गियरबॉक्स',
    gu: 'મલ્ટી-સ્પીડ હેવી કાસ્ટ આયર્ન ગિયરબોક્સ',
    pa: 'ਮਲਟੀ-ਸਪੀਡ ਹੈਵੀ ਕਾਸਟ ਆਇਰਨ ਗਿਅਰਬਾਕਸ',
    mr: 'मल्टी-स्पीड हेवी कास्ट आयर्न गिअरबॉक्स',
    te: 'మల్టీ-స్పీడ్ హెవీ కాస్ట్ ఐరన్ గేర్‌బాక్స్'
  },
  '35 - 55 HP Tractor Compatible': {
    hi: '35 - 55 HP ट्रैक्टर के लिए अनुकूल',
    gu: '35 - 55 HP ટ્રેક્ટર માટે અનુકૂળ',
    pa: '35 - 55 HP ਟਰੈਕਟਰ ਲਈ ਅਨੁਕੂਲ',
    mr: '35 - 55 HP ट्रॅक्टर सुसंगत',
    te: '35 - 55 HP ట్రాక్టర్‌కు అనుకూలం'
  },
  'Depth Control Side Skids': {
    hi: 'गहराई नियंत्रण साइड स्किड्स',
    gu: 'ઊંડાઈ નિયંત્રણ સાઇડ સ્કીડ્સ',
    pa: 'ਡੂੰਘਾਈ ਕੰਟਰੋਲ ਸਾਈਡ ਸਕਿਡਸ',
    mr: 'खोली नियंत्रण साइड स्किड्स',
    te: 'లోతు నియంత్రణ సైడ్ స్కిడ్స్'
  },
  '208cc 4-Stroke OHV Engine': {
    hi: '208cc 4-स्ट्रोक OHV पेट्रोल इंजन',
    gu: '208cc 4-સ્ટ્રોક OHV પેટ્રોલ એન્જિન',
    pa: '208cc 4-ਸਟ੍ਰੋਕ OHV ਪੈਟਰੋਲ ਇੰਜਣ',
    mr: '208cc 4-स्ट्रोक OHV पेट्रोल इंजिन',
    te: '208cc 4-స్ట్రోక్ OHV ఇంజిన్'
  },
  '900mm Adjustable Tilling Width': {
    hi: '900mm समायोज्य जुताई चौड़ाई',
    gu: '900mm એડજસ્ટેબલ ખેડાણ પહોળાઈ',
    pa: '900mm ਐਡਜਸਟੇਬਲ ਵਹਾਈ ਚੌੜਾਈ',
    mr: '900mm समायोज्य मशागत रुंदी',
    te: '900mm సర్దుబాటు చేయగల వెడల్పు'
  },
  '32 Heat-Treated Boron Blades': {
    hi: '32 हीट-ट्रीटेड बोरॉन स्टील ब्लेड्स',
    gu: '32 હીટ-ટ્રીટેડ બોરોન સ્ટીલ બ્લેડ્સ',
    pa: '32 ਹੀਟ-ਟ੍ਰੀਟਿਡ ਬੋਰਾਨ ਸਟੀਲ ਬਲੇਡ',
    mr: '32 उष्णता-उपचारित बोरॉन स्टील ब्लेड्स',
    te: '32 హీట్-ట్రీటెడ్ బోరాన్ బ్లేడ్లు'
  },
  '2 Forward + 1 Reverse Gearbox': {
    hi: '2 फॉरवर्ड + 1 रिवर्स गियरबॉक्स',
    gu: '2 ફોરવર્ડ + 1 રિવર્સ ગિયરબોક્સ',
    pa: '2 ਫਾਰਵਰਡ + 1 ਰਿਵਰਸ ਗਿਅਰਬਾਕਸ',
    mr: '2 फॉरवर्ड + 1 रिव्हर्स गिअरबॉक्स',
    te: '2 ఫార్వర్డ్ + 1 రివర్స్ గేర్‌బాక్స్'
  },
  '35,000 Liters/Hour Discharge': {
    hi: '35,000 लीटर/घंटा पानी का बहाव',
    gu: '35,000 લિટર/કલાક પાણીનો પ્રવાહ',
    pa: '35,000 ਲੀਟਰ/ਘੰਟਾ ਪਾਣੀ ਦਾ ਨਿਕਾਸ',
    mr: '35,000 लिटर/तास पाणी विसर्ग',
    te: 'గంటకు 35,000 లీటర్ల డిశ్చార్జ్'
  },
  'Up to 120 Meters Head Depth': {
    hi: '120 मीटर तक गहरी गहराई क्षमता',
    gu: '120 મીટર સુધી ઊંડી ક્ષમતા',
    pa: '120 ਮੀਟਰ ਤੱਕ ਡੂੰਘੀ ਸਮਰੱਥਾ',
    mr: '120 मीटरपर्यंत खोली क्षमता',
    te: '120 మీటర్ల వరకు లోతు సామర్థ్యం'
  },
  'IP68 Stainless Steel Body': {
    hi: 'IP68 स्टेनलेस स्टील वाटरप्रूफ बॉडी',
    gu: 'IP68 સ્ટેનલેસ સ્ટીલ વોટરપ્રૂફ બોડી',
    pa: 'IP68 ਸਟੇਨਲੈਸ ਸਟੀਲ ਵਾਟਰਪਰੂਫ ਬਾਡੀ',
    mr: 'IP68 स्टेनलेस स्टील वॉटरप्रूफ बॉडी',
    te: 'IP68 స్టెయిన్‌లెస్ స్టీల్ బాడీ'
  },
  'Smart MPPT Solar Tracking': {
    hi: 'स्मार्ट MPPT सोलर ट्रैकिंग कंट्रोलर',
    gu: 'સ્માર્ટ MPPT સોલર ટ્રેકિંગ કંટ્રોલર',
    pa: 'ਸਮਾਰਟ MPPT ਸੋਲਰ ਟਰੈਕਿੰਗ ਕੰਟਰੋਲਰ',
    mr: 'स्मार्ट MPPT सोलर ट्रॅकिंग कंट्रोलर',
    te: 'స్మార్ట్ MPPT సోలార్ ట్రాకింగ్'
  },

  // UI Badges & Buttons
  'Explore Full Machine Details': {
    hi: 'मशीन की पूरी जानकारी देखें →',
    gu: 'મશીનની સંપૂર્ણ વિગતો જુઓ →',
    pa: 'ਮਸ਼ੀਨ ਦੇ ਪੂਰੇ ਵੇਰਵੇ ਵੇਖੋ →',
    mr: 'यंत्राची संपूर्ण माहिती पहा →',
    te: 'యంత్రం పూర్తి వివరాలు చూడండి →'
  },
  'View Bank EMI Plans': {
    hi: 'बैंक ईएमआई प्लान देखें',
    gu: 'બેંક EMI પ્લાન જુઓ',
    pa: 'ਬੈਂਕ ਕਿਸ਼ਤ ਪਲਾਨ ਵੇਖੋ',
    mr: 'बँक EMI प्लॅन पहा',
    te: 'బ్యాంక్ EMI ప్లాన్‌లు చూడండి'
  },
  'Agronomy Advice': {
    hi: 'कृषि विशेषज्ञ सलाह',
    gu: 'ખેતી નિષ્ણાત સલાહ',
    pa: 'ਖੇਤੀ ਮਾਹਿਰ ਸਲਾਹ',
    mr: 'कृषी तज्ञ सल्ला',
    te: 'వ్యవసాయ సలహా'
  },
  'SPECIAL DIRECT FARM PRICE': {
    hi: 'विशेष किसान डायरेक्ट मूल्य',
    gu: 'ખાસ ખેડૂત ડાયરેક્ટ કિંમત',
    pa: 'ਵਿਸ਼ੇਸ਼ ਕਿਸਾਨ ਡਾਇਰੈਕਟ ਮੁੱਲ',
    mr: 'विशेष शेतकरी थेट किंमत',
    te: 'ప్రత్యేక రైతు ప్రత్యక్ష ధర'
  },
  '0% No-Cost EMI via Razorpay': {
    hi: '0% ब्याज किसान ईएमआई (रेजरपे)',
    gu: '0% વ્યાજ કિસાન EMI (રેઝરપે)',
    pa: '0% ਵਿਆਜ ਕਿਸਾਨ ਕਿਸ਼ਤ (ਰੇਜ਼ਰਪੇ)',
    mr: '0% व्याज शेतकरी EMI (रेझरपे)',
    te: '0% వడ్డీ కిసాన్ EMI'
  },
  'All Machinery Catalog': {
    hi: 'सभी कृषि मशीनें',
    gu: 'બધી ખેતી મશીનરી',
    pa: 'ਸਾਰੀ ਖੇਤੀ ਮਸ਼ੀਨਰੀ',
    mr: 'सर्व कृषी यंत्रसामग्री',
    te: 'అన్ని వ్యవసాయ యంత్రాలు'
  },
  'Solar Irrigation': {
    hi: 'सोलर सिंचाई पंप',
    gu: 'સોલર સિંચાઈ પંપ',
    pa: 'ਸੋਲਰ ਸਿੰਚਾਈ ਪੰਪ',
    mr: 'सोलर सिंचन पंप',
    te: 'సోలార్ సాగునీటి పంపులు'
  },
  'Power Weeders': {
    hi: 'पावर वीडर व टिलर',
    gu: 'પાવર વીડર અને ટિલર',
    pa: 'ਪਾਵਰ ਵੀਡਰ ਤੇ ਟਿਲਰ',
    mr: 'पॉवर विडर व टिलर',
    te: 'పవర్ వీడర్లు'
  },
  'Crop Sprayers': {
    hi: 'दवाई स्प्रेयर',
    gu: 'દવા સ્પ્રેયર',
    pa: 'ਸਪ੍ਰੇਅਰ ਪੰਪ',
    mr: 'औषध फवारणी यंत्रे',
    te: 'క్రాప్ స్ప్రేయర్లు'
  },
  'Helpline & FAQs': {
    hi: 'किसान हेल्पलाइन व सवाल',
    gu: 'હેલ્પલાઇન અને પ્રશ્નો',
    pa: 'ਹੈਲਪਲਾਈਨ ਤੇ ਸਵਾਲ',
    mr: 'हेल्पलाईन व प्रश्न',
    te: 'హెల్ప్‌లైన్ & ప్రశ్నలు'
  },
  'Govt. SMAM Subsidy': {
    hi: 'सरकारी SMAM सब्सिडी',
    gu: 'સરકારી SMAM સબસિડી',
    pa: 'ਸਰਕਾਰੀ SMAM ਸਬਸਿਡੀ',
    mr: 'शासकीय SMAM सबसिडी',
    te: 'ప్రభుత్వ SMAM సబ్సిడీ'
  }
};

const translations = {
  en: {
    home: 'Home',
    machinery: 'Machinery Catalog',
    categories: 'Categories',
    search_placeholder: 'Search Power Weeders, Solar Pumps, Earth Augers, Sprayers (e.g. AV-708)...',
    search: 'Search',
    account: 'My Account',
    my_profile: 'My Profile',
    my_orders: 'My Orders & Invoices',
    saved_wishlist: 'Saved Wishlist',
    support_messages: 'Support Messages',
    login: 'Farmer Login',
    logout: 'Logout',
    cart: 'Cart',
    helpline: '1800-AGRI-FARM',
    kisan_desk: 'Kisan Priority Desk',
    free_delivery_alert: 'Free Palletized Farm Delivery on orders over ₹4,999',
    add_to_cart: 'Add to Cart',
    buy_now: 'Buy Now',
    sold_out: 'Sold Out',
    in_stock: 'In Stock & Ready for Immediate Dispatch',
    low_stock: 'Low Stock: Few machines remaining',
    out_of_stock: 'Out of Stock',
    verified_reviews: '100% Verified Farmer Reviews',
    emi_starting: 'EASY KISAN EMI AVAILABLE',
    view_emi_plans: 'View EMI Plans',
    ask_specialist: 'Ask Specialist / Query',
    whatsapp_advisor: 'WhatsApp Advisor',
    share_product: 'Share Farm Equipment',
    share: 'Share',
    model: 'Model',
    sku: 'SKU',
    save: 'Save',
    extra_discount: 'Special Offer',
    incl_gst: 'Incl. GST',
    overview_title: 'Product Overview & Operating Capabilities',
    specifications_title: 'Technical Specifications & Engineering Matrix',
    applications_title: 'Ideal Crop & Field Applications',
    key_features: 'Key Engineering Features',
    whats_in_box: "What's Included in the Box",
    faq_title: 'Frequently Asked Farmer Questions',
    warranty: '1 Year Manufacturer Warranty',
    free_delivery: 'Free Delivery',
    shopping_cart: 'Shopping Cart',
    cart_empty: 'Your Cart is Empty',
    browse_machinery: 'Browse Farm Equipment',
    order_summary: 'Order Summary',
    subtotal: 'Items Subtotal',
    estimated_gst: 'Estimated GST (Included)',
    delivery_charge: 'Farm Delivery',
    proceed_to_checkout: 'Proceed to Checkout',
    checkout_title: 'Farm Equipment Checkout',
    step1_auth: 'Step 1: Farmer Sign In Required to Confirm Order',
    existing_login: 'Existing Customer Login',
    new_registration: 'New Farmer Registration',
    delivery_address: 'Farm Delivery Address',
    payment_mode: 'Select Payment Mode',
    confirm_order: 'Confirm Farm Delivery Order',
    pay_via_razorpay: 'Pay via Razorpay',
    apply_coupon: 'Apply Discount Coupon',
    orders_title: 'My Orders & Live Shipment Tracking',
    no_orders: 'No Farm Equipment Orders Placed Yet',
    order_number: 'Order Number',
    order_status: 'Live Shipment Status',
    reorder: 'Reorder All',
    view_timeline: 'View Full Logistics Timeline',
    hide_timeline: 'Hide Milestone Details',
    profile_title: 'Farmer Profile & Details',
    saved_addresses: 'Saved Farm Addresses',
    security_password: 'Security & Password',
    theme: 'Theme',
    light_mode: 'Day Mode',
    dark_mode: 'Night Farm Mode',
    language: 'Language',
    explore_machine: 'Explore Full Machine Details',
    view_emi_plans_btn: 'View Bank EMI Plans',
    agronomy_advice: 'Agronomy Advice',
    deal_ends_in: 'Ends in',
    special_farm_price: 'SPECIAL DIRECT FARM PRICE',
    no_cost_emi_badge: '0% No-Cost EMI via Razorpay',
    monthly_emi_text: 'EMI from',
    all_machinery_catalog: 'All Machinery Catalog',
    solar_irrigation: 'Solar Irrigation',
    power_weeders: 'Power Weeders',
    crop_sprayers: 'Crop Sprayers',
    helpline_faqs: 'Helpline & FAQs',
    govt_subsidy: 'Govt. SMAM Subsidy',
    today_deals: "Today's Lightning Machinery Deals",
    combo_save: 'COMBO SAVE',
    add_all_to_cart: 'Add All To Cart',
    frequently_bought_together: 'Frequently Bought Together',
    claimed: 'Claimed',
    claim_deal_now: 'Claim Deal Now'
  },
  hi: {
    home: 'मुख्य पृष्ठ',
    machinery: 'कृषि मशीनें',
    categories: 'श्रेणियां',
    search_placeholder: 'पावर वीडर, सोलर पंप, स्प्रेयर, रोटावेटर खोजें (उदा. AV-708)...',
    search: 'खोजें',
    account: 'मेरा खाता',
    my_profile: 'किसान प्रोफाइल',
    my_orders: 'मेरे ऑर्डर्स व बिल',
    saved_wishlist: 'पसंदीदा मशीनें',
    support_messages: 'किसान सहायता संदेश',
    login: 'किसान लॉगिन',
    logout: 'लॉगआउट',
    cart: 'कार्ट',
    helpline: '1800-AGRI-FARM (टोल-फ्री)',
    kisan_desk: 'किसान प्राथमिकता सेवा',
    free_delivery_alert: '₹4,999 से अधिक के ऑर्डर पर पूरे भारत में मुफ्त फार्म डिलीवरी',
    add_to_cart: 'कार्ट में जोड़ें',
    buy_now: 'अभी खरीदें',
    sold_out: 'स्टॉक समाप्त',
    in_stock: '✓ स्टॉक में उपलब्ध - तुरंत डिस्पैच',
    low_stock: '⚡ सीमित स्टॉक: केवल कुछ मशीनें शेष',
    out_of_stock: 'स्टॉक समाप्त',
    verified_reviews: '100% सत्यापित किसान समीक्षाएं',
    emi_starting: 'आसान किसान ईएमआई (0% ब्याज)',
    view_emi_plans: 'ईएमआई प्लान देखें',
    ask_specialist: 'कृषि विशेषज्ञ से पूछें',
    whatsapp_advisor: 'व्हाट्सएप पर बात करें',
    share_product: 'मशीन शेयर करें',
    share: 'शेयर',
    model: 'मॉडल',
    sku: 'एसकेयू',
    save: 'बचत',
    extra_discount: 'विशेष छूट',
    incl_gst: 'जीएसटी सहित',
    overview_title: 'उत्पाद विवरण एवं कार्य क्षमता',
    specifications_title: 'तकनीकी विशेषताएं व इंजन विवरण',
    applications_title: 'उपयुक्त फसलें एवं खेत अनुप्रयोग',
    key_features: 'प्रमुख विशेषताएं',
    whats_in_box: 'बॉक्स में क्या मिलेगा',
    faq_title: 'किसानों के अक्सर पूछे जाने वाले सवाल',
    warranty: '1 वर्ष की अधिकृत कंपनी वारंटी',
    free_delivery: 'मुफ्त फार्म डिलीवरी',
    shopping_cart: 'शॉपिंग कार्ट',
    cart_empty: 'आपकी कार्ट खाली है',
    browse_machinery: 'कृषि उपकरण कैटलॉग देखें',
    order_summary: 'ऑर्डर सारांश',
    subtotal: 'मशीनों की कुल कीमत',
    estimated_gst: 'अनुमानित जीएसटी (शामिल)',
    delivery_charge: 'फार्म डिलीवरी शुल्क',
    proceed_to_checkout: 'चेकआउट के लिए आगे बढ़ें',
    checkout_title: 'कृषि मशीनरी चेकआउट व ऑर्डर पुष्टि',
    step1_auth: 'स्टेप 1: ऑर्डर पुष्टि के लिए किसान लॉगिन अनिवार्य',
    existing_login: 'पुराना ग्राहक लॉगिन',
    new_registration: 'नया किसान खाता बनाएं',
    delivery_address: 'खेत का डिलीवरी पता',
    payment_mode: 'भुगतान का तरीका चुनें',
    confirm_order: 'फार्म डिलीवरी ऑर्डर पक्का करें',
    pay_via_razorpay: 'रेजरपे से ऑनलाइन भुगतान करें',
    apply_coupon: 'कूपन कोड लगाएं',
    orders_title: 'मेरे ऑर्डर्स एवं लाइव डिलीवरी ट्रैकिंग',
    no_orders: 'इस खाते में अभी कोई ऑर्डर नहीं है',
    order_number: 'ऑर्डर नंबर',
    order_status: 'लाइव डिलीवरी स्थिति',
    reorder: 'दोबारा ऑर्डर करें',
    view_timeline: 'पूरी ट्रैकिंग देखें',
    hide_timeline: 'ट्रैकिंग छुपाएं',
    profile_title: 'किसान प्रोफाइल और जानकारी',
    saved_addresses: 'सहेजे गए खेत के पते',
    security_password: 'सुरक्षा और पासवर्ड',
    theme: 'थीम',
    light_mode: 'दिन मोड (लाइट)',
    dark_mode: 'नाइट फार्म मोड (डार्क)',
    language: 'भाषा',
    explore_machine: 'मशीन की पूरी जानकारी देखें →',
    view_emi_plans_btn: 'बैंक ईएमआई प्लान देखें',
    agronomy_advice: 'कृषि विशेषज्ञ सलाह',
    deal_ends_in: 'समाप्ति शेष',
    special_farm_price: 'विशेष किसान डायरेक्ट मूल्य',
    no_cost_emi_badge: '0% ब्याज किसान ईएमआई (रेजरपे)',
    monthly_emi_text: 'किस्त मात्र',
    all_machinery_catalog: 'सभी कृषि मशीनें',
    solar_irrigation: 'सोलर सिंचाई पंप',
    power_weeders: 'पावर वीडर व टिलर',
    crop_sprayers: 'दवाई स्प्रेयर',
    helpline_faqs: 'किसान हेल्पलाइन व सवाल',
    govt_subsidy: 'सरकारी SMAM सब्सिडी',
    today_deals: 'आज के विशेष लाइटनिंग मशीनरी सौदे',
    combo_save: 'कॉम्बो बचत',
    add_all_to_cart: 'सभी मशीनें कार्ट में जोड़ें',
    frequently_bought_together: 'अक्सर साथ खरीदी जाने वाली मशीनें',
    claimed: 'बुक हो चुका',
    claim_deal_now: 'डील बुक करें'
  },
  gu: {
    home: 'મુખ્ય પૃષ્ઠ',
    machinery: 'ખેતી મશીનરી',
    categories: 'કેટેગરીઝ',
    search_placeholder: 'પાવર વીડર, સોલર પંપ, સ્પ્રેયર શોધો...',
    search: 'શોધો',
    account: 'મારું ખાતું',
    my_profile: 'ખેડૂત પ્રોફાઇલ',
    my_orders: 'મારા ઓર્ડર અને બિલ',
    saved_wishlist: 'મનપસંદ મશીનરી',
    support_messages: 'સહાયતા મેસેજ',
    login: 'ખેડૂત લૉગિન',
    logout: 'લૉગઆઉટ',
    cart: 'કાર્ટ',
    helpline: '1800-AGRI-FARM',
    kisan_desk: 'કિસાન પ્રાયોરિટી ડેસ્ક',
    free_delivery_alert: '₹4,999 થી વધુના ઓર્ડર પર સમગ્ર ગુજરાત અને ભારતમાં ફ્રી ડિલિવરી',
    add_to_cart: 'કાર્ટમાં ઉમેરો',
    buy_now: 'હમણાં ખરીદો',
    sold_out: 'સ્ટોક ખલાસ',
    in_stock: '✓ સ્ટોકમાં ઉપલબ્ધ - તુરંત ડિસ્પેચ',
    low_stock: '⚡ મર્યાદિત સ્ટોક',
    out_of_stock: 'સ્ટોક ખલાસ',
    verified_reviews: '100% ચકાસાયેલ ખેડૂત રિવ્યુ',
    emi_starting: 'સરળ કિસાન ઈએમઆઈ (0% વ્યાજ)',
    view_emi_plans: 'ઈએમઆઈ પ્લાન જુઓ',
    ask_specialist: 'ખેતી નિષ્ણાતને પૂછો',
    whatsapp_advisor: 'વોટ્સએપ સહાયક',
    share_product: 'મશીન શેર કરો',
    share: 'શેર',
    model: 'મોડલ',
    sku: 'એસકેયુ',
    save: 'બચત',
    extra_discount: 'વિશેષ ઓફર',
    incl_gst: 'જીએસટી સહિત',
    overview_title: 'પ્રોડક્ટ માહિતી અને કાર્યક્ષમતા',
    specifications_title: 'ટેકનિકલ વિગતો',
    applications_title: 'અનુકૂળ પાક અને ખેત ઉપયોગ',
    key_features: 'મુખ્ય વિશેષતાઓ',
    whats_in_box: 'બોક્સમાં શું મળશે',
    faq_title: 'ખેડૂતોના સામાન્ય પ્રશ્નો',
    warranty: '1 વર્ષ કંપની વોરંટી',
    free_delivery: 'ફ્રી ફાર્મ ડિલિવરી',
    shopping_cart: 'શોપિંગ કાર્ટ',
    cart_empty: 'તમારી કાર્ટ ખાલી છે',
    browse_machinery: 'મશીનરી કેટેલોગ જુઓ',
    order_summary: 'ઓર્ડર સારાંશ',
    subtotal: 'કુલ રકમ',
    estimated_gst: 'અંદાજિત જીએસટી (સમાવિષ્ટ)',
    delivery_charge: 'ડિલિવરી ચાર્જ',
    proceed_to_checkout: 'ચેકઆઉટ કરો',
    checkout_title: 'ઓર્ડર અને ડિલિવરી કન્ફર્મેશન',
    step1_auth: 'સ્ટેપ 1: ઓર્ડર માટે ખેડૂત લૉગિન જરૂરી છે',
    existing_login: 'ગ્રાહક લૉગિન',
    new_registration: 'નવા ખેડૂત રજીસ્ટ્રેશન',
    delivery_address: 'ડિલિવરી સરનામું',
    payment_mode: 'પેમેન્ટ પદ્ધતિ પસંદ કરો',
    confirm_order: 'ઓર્ડર કન્ફર્મ કરો',
    pay_via_razorpay: 'રેઝરપેથી ઓનલાઇન ચૂકવો',
    apply_coupon: 'કૂપન કોડ લાગુ કરો',
    orders_title: 'મારા ઓર્ડર્સ અને લાઇવ ટ્રેકિંગ',
    no_orders: 'હજી સુધી કોઈ ઓર્ડર નથી',
    order_number: 'ઓર્ડર નંબર',
    order_status: 'ડિલિવરી સ્થિતિ',
    reorder: 'ફરીથી ઓર્ડર કરો',
    view_timeline: 'ટ્રેકિંગ વિગતો જુઓ',
    hide_timeline: 'ટ્રેકિંગ છુપાવો',
    profile_title: 'ખેડૂત પ્રોફાઇલ',
    saved_addresses: 'સાચવેલા સરનામાં',
    security_password: 'સુરક્ષા અને પાસવર્ડ',
    theme: 'થીમ',
    light_mode: 'ડે મોડ',
    dark_mode: 'નાઇટ ફાર્મ મોડ',
    language: 'ભાષા',
    explore_machine: 'મશીનની સંપૂર્ણ વિગતો જુઓ →',
    view_emi_plans_btn: 'બેંક EMI પ્લાન જુઓ',
    agronomy_advice: 'ખેતી નિષ્ણાત સલાહ',
    deal_ends_in: 'સમાપ્તિ બાકી',
    special_farm_price: 'ખાસ ખેડૂત ડાયરેક્ટ કિંમત',
    no_cost_emi_badge: '0% વ્યાજ કિસાન EMI (રેઝરપે)',
    monthly_emi_text: 'હપ્તો માત્ર',
    all_machinery_catalog: 'બધી ખેતી મશીનરી',
    solar_irrigation: 'સોલર સિંચાઈ પંપ',
    power_weeders: 'પાવર વીડર અને ટિલર',
    crop_sprayers: 'દવા સ્પ્રેયર',
    helpline_faqs: 'હેલ્પલાઇન અને પ્રશ્નો',
    govt_subsidy: 'સરકારી SMAM સબસિડી',
    today_deals: 'આજના ખાસ મશીનરી સોદા',
    combo_save: 'કોમ્બો બચત',
    add_all_to_cart: 'બધા મશીન કાર્ટમાં ઉમેરો',
    frequently_bought_together: 'વારંવાર સાથે ખરીદવામાં આવતી મશીનરી',
    claimed: 'બુક થયું',
    claim_deal_now: 'ડીલ બુક કરો'
  },
  pa: {
    home: 'ਮੁੱਖ ਪੰਨਾ',
    machinery: 'ਖੇਤੀ ਮਸ਼ੀਨਰੀ',
    categories: 'ਕੈਟਾਗਰੀਆਂ',
    search_placeholder: 'ਪਾਵਰ ਵੀਡਰ, ਸੋਲਰ ਪੰਪ, ਬਰੱਸ਼ ਕਟਰ ਖੋਜੋ...',
    search: 'ਖੋਜੋ',
    account: 'ਮੇਰਾ ਖਾਤਾ',
    my_profile: 'ਕਿਸਾਨ ਪ੍ਰੋਫਾਈਲ',
    my_orders: 'ਮੇਰੇ ਆਰਡਰ ਤੇ ਬਿੱਲ',
    saved_wishlist: 'ਪਸੰਦੀਦਾ ਮਸ਼ੀਨਾਂ',
    support_messages: 'ਸਹਾਇਤਾ ਸੁਨੇਹੇ',
    login: 'ਕਿਸਾਨ ਲੌਗਇਨ',
    logout: 'ਲੌਗਆਉਟ',
    cart: 'ਕਾਰਟ',
    helpline: '1800-AGRI-FARM',
    kisan_desk: 'ਕਿਸਾਨ ਡੈਸਕ',
    free_delivery_alert: '₹4,999 ਤੋਂ ਵੱਧ ਦੇ ਆਰਡਰ ਤੇ ਮੁਫਤ ਫਾਰਮ ਡਿਲਿਵਰੀ',
    add_to_cart: 'ਕਾਰਟ ਵਿੱਚ ਪਾਓ',
    buy_now: 'ਹੁਣੇ ਖਰੀਦੋ',
    sold_out: 'ਸਟਾਕ ਖਤਮ',
    in_stock: '✓ ਸਟਾਕ ਵਿੱਚ ਉਪਲਬਧ',
    low_stock: '⚡ ਸੀਮਤ ਸਟਾਕ',
    out_of_stock: 'ਸਟਾਕ ਖਤਮ',
    verified_reviews: '100% ਪ੍ਰਮਾਣਿਤ ਕਿਸਾਨ ਸਮੀਖਿਆਵਾਂ',
    emi_starting: 'ਸੌਖੀ ਕਿਸਾਨ ਕਿਸ਼ਤ (0% ਵਿਆਜ)',
    view_emi_plans: 'ਕਿਸ਼ਤ ਪਲਾਨ ਵੇਖੋ',
    ask_specialist: 'ਮਾਹਿਰ ਤੋਂ ਪੁੱਛੋ',
    whatsapp_advisor: 'ਵਟਸਐਪ ਸਲਾਹਕਾਰ',
    share_product: 'ਮਸ਼ੀਨ ਸ਼ੇਅਰ ਕਰੋ',
    share: 'ਸ਼ੇਅਰ',
    model: 'ਮਾਡਲ',
    sku: 'ਐਸਕੇਯੂ',
    save: 'ਬੱਚਤ',
    extra_discount: 'ਵਿਸ਼ੇਸ਼ ਛੋਟ',
    incl_gst: 'ਜੀਐਸਟੀ ਸਮੇਤ',
    overview_title: 'ਉਤਪਾਦ ਵੇਰਵਾ ਤੇ ਸਮਰੱਥਾ',
    specifications_title: 'ਤਕਨੀਕੀ ਵੇਰਵੇ',
    applications_title: 'ਢੁਕਵੀਂ ਫਸਲ ਤੇ ਖੇਤ ਵਰਤੋਂ',
    key_features: 'ਮੁੱਖ ਵਿਸ਼ੇਸ਼ਤਾਵਾਂ',
    whats_in_box: 'ਡੱਬੇ ਵਿੱਚ ਕੀ ਮਿਲੇਗਾ',
    faq_title: 'ਕਿਸਾਨਾਂ ਦੇ ਅਕਸਰ ਪੁੱਛੇ ਜਾਂਦੇ ਸਵਾਲ',
    warranty: '1 ਸਾਲ ਕੰਪਨੀ ਵਾਰੰਟੀ',
    free_delivery: 'ਮੁਫਤ ਡਿਲਿਵਰੀ',
    shopping_cart: 'ਸ਼ਾਪਿੰਗ ਕਾਰਟ',
    cart_empty: 'ਤੁਹਾਡੀ ਕਾਰਟ ਖਾਲੀ ਹੈ',
    browse_machinery: 'ਮਸ਼ੀਨਰੀ ਕੈਟਾਲਾਗ ਵੇਖੋ',
    order_summary: 'ਆਰਡਰ ਸੰਖੇਪ',
    subtotal: 'ਕੁੱਲ ਰਕਮ',
    estimated_gst: 'ਜੀਐਸਟੀ (ਸ਼ਾਮਲ)',
    delivery_charge: 'ਡਿਲਿਵਰੀ ਚਾਰਜ',
    proceed_to_checkout: 'ਚੈੱਕਆਉਟ ਲਈ ਅੱਗੇ ਵਧੋ',
    checkout_title: 'ਆਰਡਰ ਅਤੇ ਡਿਲਿਵਰੀ ਪੁਸ਼ਟੀ',
    step1_auth: 'ਕਦਮ 1: ਆਰਡਰ ਲਈ ਕਿਸਾਨ ਲੌਗਇਨ ਲਾਜ਼ਮੀ ਹੈ',
    existing_login: 'ਗਾਹਕ ਲੌਗਇਨ',
    new_registration: 'ਨਵਾਂ ਕਿਸਾਨ ਰਜਿਸਟ੍ਰੇਸ਼ਨ',
    delivery_address: 'ਖੇਤ ਦਾ ਡਿਲਿਵਰੀ ਪਤਾ',
    payment_mode: 'ਭੁਗਤਾਨ ਦਾ ਤਰੀਕਾ ਚੁਣੋ',
    confirm_order: 'ਆਰਡਰ ਪੱਕਾ ਕਰੋ',
    pay_via_razorpay: 'ਰੇਜ਼ਰਪੇ ਨਾਲ ਆਨਲਾਈਨ ਭੁਗਤਾਨ ਕਰੋ',
    apply_coupon: 'ਕੂਪਨ ਕੋਡ ਲਗਾਓ',
    orders_title: 'ਮੇਰੇ ਆਰਡਰ ਤੇ ਲਾਈਵ ਟਰੈਕਿੰਗ',
    no_orders: 'ਕੋਈ ਆਰਡਰ ਨਹੀਂ ਮਿਲਿਆ',
    order_number: 'ਆਰਡਰ ਨੰਬਰ',
    order_status: 'ਡਿਲਿਵਰੀ ਸਥਿਤੀ',
    reorder: 'ਮੁੜ ਆਰਡਰ ਕਰੋ',
    view_timeline: 'ਪੂਰੀ ਟਰੈਕਿੰਗ ਵੇਖੋ',
    hide_timeline: 'ਟਰੈਕਿੰਗ ਛੁਪਾਓ',
    profile_title: 'ਕਿਸਾਨ ਪ੍ਰੋਫਾਈਲ',
    saved_addresses: 'ਸੁਰੱਖਿਅਤ ਪਤੇ',
    security_password: 'ਸੁਰੱਖਿਆ ਤੇ ਪਾਸਵਰਡ',
    theme: 'ਥੀਮ',
    light_mode: 'ਡੇਅ ਮੋਡ',
    dark_mode: 'ਨਾਈਟ ਫਾਰਮ ਮੋਡ',
    language: 'ਭਾਸ਼ਾ',
    explore_machine: 'ਮਸ਼ੀਨ ਦੇ ਪੂਰੇ ਵੇਰਵੇ ਵੇਖੋ →',
    view_emi_plans_btn: 'ਬੈਂਕ ਕਿਸ਼ਤ ਪਲਾਨ ਵੇਖੋ',
    agronomy_advice: 'ਖੇਤੀ ਮਾਹਿਰ ਸਲਾਹ',
    deal_ends_in: 'ਸਮਾਪਤੀ ਬਾਕੀ',
    special_farm_price: 'ਵਿਸ਼ੇਸ਼ ਕਿਸਾਨ ਡਾਇਰੈਕਟ ਮੁੱਲ',
    no_cost_emi_badge: '0% ਵਿਆਜ ਕਿਸਾਨ ਕਿਸ਼ਤ (ਰੇਜ਼ਰਪੇ)',
    monthly_emi_text: 'ਕਿਸ਼ਤ ਮਾਤਰ',
    all_machinery_catalog: 'ਸਾਰੀ ਖੇਤੀ ਮਸ਼ੀਨਰੀ',
    solar_irrigation: 'ਸੋਲਰ ਸਿੰਚਾਈ ਪੰਪ',
    power_weeders: 'ਪਾਵਰ ਵੀਡਰ ਤੇ ਟਿਲਰ',
    crop_sprayers: 'ਸਪ੍ਰੇਅਰ ਪੰਪ',
    helpline_faqs: 'ਹੈਲਪਲਾਈਨ ਤੇ ਸਵਾਲ',
    govt_subsidy: 'ਸਰਕਾਰੀ SMAM ਸਬਸਿਡੀ',
    today_deals: 'ਅੱਜ ਦੇ ਵਿਸ਼ੇਸ਼ ਮਸ਼ੀਨਰੀ ਸੌਦੇ',
    combo_save: 'ਕੰਬੋ ਬੱਚਤ',
    add_all_to_cart: 'ਸਾਰੀਆਂ ਮਸ਼ੀਨਾਂ ਕਾਰਟ ਵਿੱਚ ਪਾਓ',
    frequently_bought_together: 'ਅਕਸਰ ਇਕੱਠੀਆਂ ਖਰੀਦੀਆਂ ਜਾਣ ਵਾਲੀਆਂ ਮਸ਼ੀਨਾਂ',
    claimed: 'ਬੁੱਕ ਹੋ ਗਿਆ',
    claim_deal_now: 'ਸੌਦਾ ਬੁੱਕ ਕਰੋ'
  },
  mr: {
    home: 'मुख्यपृष्ठ',
    machinery: 'कृषी यंत्रसामग्री',
    categories: 'श्रेणी',
    search_placeholder: 'पॉवर विडर, सोलर पंप, स्प्रेअर शोधा...',
    search: 'शोधा',
    account: 'माझे खाते',
    my_profile: 'शेतकरी प्रोफाइल',
    my_orders: 'माझ्या ऑर्डर्स आणि बिले',
    saved_wishlist: 'आवडती यंत्रे',
    support_messages: 'मदत संदेश',
    login: 'शेतकरी लॉगिन',
    logout: 'लॉगआउट',
    cart: 'कार्ट',
    helpline: '1800-AGRI-FARM',
    kisan_desk: 'किसान डेस्क',
    free_delivery_alert: '₹4,999 पेक्षा जास्त ऑर्डरवर मोफत फार्म डिलिव्हरी',
    add_to_cart: 'कार्टमध्ये जोडा',
    buy_now: 'आत्ताच खरेदी करा',
    sold_out: 'स्टॉक संपला',
    in_stock: '✓ स्टॉकमध्ये उपलब्ध',
    low_stock: '⚡ मर्यादित स्टॉक',
    out_of_stock: 'स्टॉक संपला',
    verified_reviews: '100% सत्यापित शेतकरी पुनरावलोकने',
    emi_starting: 'सोपे किसान ईएमआय (0% व्याज)',
    view_emi_plans: 'ईएमआय प्लॅन पहा',
    ask_specialist: 'तज्ञांना विचारा',
    whatsapp_advisor: 'व्हॉट्सअॅप सल्लागार',
    share_product: 'यंत्र शेअर करा',
    share: 'शेअर',
    model: 'मॉडेल',
    sku: 'एसकेयू',
    save: 'बचत',
    extra_discount: 'विशेष सूट',
    incl_gst: 'जीएसटी सह',
    overview_title: 'उत्पादन तपशील व क्षमता',
    specifications_title: 'तांत्रिक तपशील',
    applications_title: 'योग्य पिके व वापर',
    key_features: 'प्रमुख वैशिष्ट्ये',
    whats_in_box: 'बॉक्समध्ये काय मिळेल',
    faq_title: 'वारंवार विचारले जाणारे प्रश्न',
    warranty: '1 वर्ष कंपनी वॉरंटी',
    free_delivery: 'मोफत डिलिव्हरी',
    shopping_cart: 'शॉपिंग कार्ट',
    cart_empty: 'आपली कार्ट रिकामी आहे',
    browse_machinery: 'यंत्रसामग्री कॅटलॉग पहा',
    order_summary: 'ऑर्डर सारांश',
    subtotal: 'एकूण रक्कम',
    estimated_gst: 'जीएसटी (समाविष्ट)',
    delivery_charge: 'डिलिव्हरी शुल्क',
    proceed_to_checkout: 'चेकआउट करा',
    checkout_title: 'ऑर्डर व डिलिव्हरी पुष्टी',
    step1_auth: 'पायरी 1: ऑर्डरसाठी शेतकरी लॉगिन आवश्यक',
    existing_login: 'ग्राहक लॉगिन',
    new_registration: 'नवीन शेतकरी नोंदणी',
    delivery_address: 'डिलिव्हरी पत्ता',
    payment_mode: 'पेमेंट पद्धत निवडा',
    confirm_order: 'ऑर्डर निश्चित करा',
    pay_via_razorpay: 'रेझरपे द्वारे ऑनलाइन भरा',
    apply_coupon: 'कूपन कोड लागू करा',
    orders_title: 'माझ्या ऑर्डर्स आणि थेट ट्रॅकिंग',
    no_orders: 'अद्याप कोणतीही ऑर्डर नाही',
    order_number: 'ऑर्डर क्रमांक',
    order_status: 'डिलिव्हरी स्थिती',
    reorder: 'पुन्हा ऑर्डर करा',
    view_timeline: 'पूर्ण ट्रॅकिंग पहा',
    hide_timeline: 'ट्रॅकिंग लपवा',
    profile_title: 'शेतकरी प्रोफाइल',
    saved_addresses: 'जतन केलेले पत्ते',
    security_password: 'सुरक्षा आणि पासवर्ड',
    theme: 'थीम',
    light_mode: 'दिवस मोड',
    dark_mode: 'रात्र फार्म मोड',
    language: 'भाषा',
    explore_machine: 'यंत्राची संपूर्ण माहिती पहा →',
    view_emi_plans_btn: 'बँक EMI प्लॅन पहा',
    agronomy_advice: 'कृषी तज्ञ सल्ला',
    deal_ends_in: 'समाप्ती बाकी',
    special_farm_price: 'विशेष शेतकरी थेट किंमत',
    no_cost_emi_badge: '0% व्याज शेतकरी EMI (रेझरपे)',
    monthly_emi_text: 'हप्ता फक्त',
    all_machinery_catalog: 'सर्व कृषी यंत्रसामग्री',
    solar_irrigation: 'सोलर सिंचन पंप',
    power_weeders: 'पॉवर विडर व टिलर',
    crop_sprayers: 'औषध फवारणी यंत्रे',
    helpline_faqs: 'हेल्पलाईन व प्रश्न',
    govt_subsidy: 'शासकीय SMAM सबसिडी',
    today_deals: 'आजचे विशेष यंत्रसामग्री सौदे',
    combo_save: 'कॉम्बो बचत',
    add_all_to_cart: 'सर्व यंत्रे कार्टमध्ये जोडा',
    frequently_bought_together: 'वारंवार एकत्र खरेदी केली जाणारी यंत्रे',
    claimed: 'बुक झाले',
    claim_deal_now: 'सौदा बुक करा'
  },
  te: {
    home: 'హోమ్‌పేజీ',
    machinery: 'వ్యవసాయ యంత్రాలు',
    categories: 'కేటగిరీలు',
    search_placeholder: 'పవర్ వీడర్, సోలార్ పంప్, స్ప్రేయర్ శోధించండి...',
    search: 'శోధన',
    account: 'నా ఖాతా',
    my_profile: 'రైతు ప్రొఫైల్',
    my_orders: 'నా ఆర్డర్లు & బిల్లులు',
    saved_wishlist: 'కోరికల జాబితా',
    support_messages: 'సహాయ సందేశాలు',
    login: 'రైతు లాగిన్',
    logout: 'లాగౌట్',
    cart: 'కార్ట్',
    helpline: '1800-AGRI-FARM',
    kisan_desk: 'కిసాన్ డెస్క్',
    free_delivery_alert: '₹4,999 పైబడి ఉచిత ఫార్మ్ డెలివరీ',
    add_to_cart: 'కార్ట్‌కు జోడించు',
    buy_now: 'ఇప్పుడే కొనండి',
    sold_out: 'స్టాక్ ముగిసింది',
    in_stock: '✓ స్టాక్‌లో ఉంది',
    low_stock: '⚡ పరిమిత స్టాక్',
    out_of_stock: 'స్టాక్ ముగిసింది',
    verified_reviews: '100% ధృవీకరించబడిన రైతు సమీక్షలు',
    emi_starting: 'సులభ కిసాన్ EMI (0% వడ్డీ)',
    view_emi_plans: 'EMI ప్లాన్‌లు చూడండి',
    ask_specialist: 'నిపుణుడిని అడగండి',
    whatsapp_advisor: 'వాట్సాప్ సలహాదారు',
    share_product: 'యంత్రాన్ని షేర్ చేయండి',
    share: 'షేర్',
    model: 'మోడల్',
    sku: 'SKU',
    save: 'ఆదా',
    extra_discount: 'ప్రత్యేక తగ్గింపు',
    incl_gst: 'జీఎస్టీతో సహా',
    overview_title: 'ఉత్పత్తి వివరాలు & సామర్థ్యం',
    specifications_title: 'సాంకేతిక వివరాలు',
    applications_title: 'అనుకూల పంటలు & ఉపయోగాలు',
    key_features: 'ముఖ్య లక్షణాలు',
    whats_in_box: 'బాక్స్‌లో ఏముంటుంది',
    faq_title: 'రైతులు తరచుగా అడిగే ప్రశ్నలు',
    warranty: '1 సంవత్సరం కంపెనీ వారంటీ',
    free_delivery: 'ఉచిత డెలివరీ',
    shopping_cart: 'షాపింగ్ కార్ట్',
    cart_empty: 'మీ కార్ట్ ఖాళీగా ఉంది',
    browse_machinery: 'యంత్రాల జాబితా చూడండి',
    order_summary: 'ఆర్డర్ సారాంశం',
    subtotal: 'మొత్తం ధర',
    estimated_gst: 'అంచనా జీఎస్టీ',
    delivery_charge: 'డెలివరీ ఛార్జీ',
    proceed_to_checkout: 'చెక్‌అవుట్‌కు వెళ్లండి',
    checkout_title: 'ఆర్డర్ & డెలివరీ నిర్ధారణ',
    step1_auth: 'దశ 1: ఆర్డర్ కోసం రైతు లాగిన్ అవసరం',
    existing_login: 'కస్టమర్ లాగిన్',
    new_registration: 'కొత్త రైతు నమోదు',
    delivery_address: 'డెలివరీ చిరునామా',
    payment_mode: 'చెల్లింపు విధానం ఎంచుకోండి',
    confirm_order: 'ఆర్డర్ నిర్ధారించండి',
    pay_via_razorpay: 'రేజర్‌పే ద్వారా చెల్లించండి',
    apply_coupon: 'కూపన్ కోడ్ వర్తింపజేయండి',
    orders_title: 'నా ఆర్డర్లు & లైవ్ ట్రాకింగ్',
    no_orders: 'ఆర్డర్లు ఏవీ లేవు',
    order_number: 'ఆర్డర్ నంబర్',
    order_status: 'డెలివరీ స్థితి',
    reorder: 'మళ్లీ ఆర్డర్ చేయండి',
    view_timeline: 'పూర్తి ట్రాకింగ్ చూడండి',
    hide_timeline: 'ట్రాకింగ్ దాచండి',
    profile_title: 'రైతు ప్రొఫైల్',
    saved_addresses: 'భద్రపరిచిన చిరునామాలు',
    security_password: 'భద్రత & పాస్‌వర్డ్',
    theme: 'థీమ్',
    light_mode: 'డే మోਡ',
    dark_mode: 'నైట్ ఫార్మ్ మోడ్',
    language: 'భాష',
    explore_machine: 'యంత్రం పూర్తి వివరాలు చూడండి →',
    view_emi_plans_btn: 'బ్యాంక్ EMI ప్లాన్‌లు చూడండి',
    agronomy_advice: 'వ్యవసాయ సలహా',
    deal_ends_in: 'ముగింపు సమయం',
    special_farm_price: 'ప్రత్యేక రైతు ప్రత్యక్ష ధర',
    no_cost_emi_badge: '0% వడ్డీ కిసాన్ EMI',
    monthly_emi_text: 'నెలవారీ వాయిదా',
    all_machinery_catalog: 'అన్ని వ్యవసాయ యంత్రాలు',
    solar_irrigation: 'సోలార్ సాగునీటి పంపులు',
    power_weeders: 'పవర్ వీడర్లు',
    crop_sprayers: 'క్రాప్ స్ప్రేయర్లు',
    helpline_faqs: 'హెల్ప్‌లైన్ & ప్రశ్నలు',
    govt_subsidy: 'ప్రభుత్వ SMAM సబ్సిడీ',
    today_deals: 'నేటి ప్రత్యేక యంత్రాల ఆఫర్లు',
    combo_save: 'కాంబో ఆదా',
    add_all_to_cart: 'అన్ని యంత్రాలను కార్ట్‌కు జోడించండి',
    frequently_bought_together: 'తరచుగా కలిసి కొనుగోలు చేసే యంత్రాలు',
    claimed: 'బుక్ చేయబడింది',
    claim_deal_now: 'ఆఫర్ పొందండి'
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    try {
      const saved = localStorage.getItem('agri_lang');
      if (saved && translations[saved]) {
        return saved;
      }
      return 'en';
    } catch (e) {
      return 'en';
    }
  });

  useEffect(() => {
    try {
      localStorage.setItem('agri_lang', language);
    } catch (e) {}
  }, [language]);

  const t = (key, fallback = '') => {
    const langDict = translations[language] || translations.en;
    if (langDict && langDict[key]) return langDict[key];
    if (translations.en[key]) return translations.en[key];
    return fallback || key;
  };

  /**
   * Translate any dynamic text / phrase / product title into current language
   */
  const tr = (text) => {
    if (!text || typeof text !== 'string') return text;
    if (language === 'en') return text;

    const trimmed = text.trim();

    // Check direct phrase dictionary
    if (phraseDictionary[trimmed] && phraseDictionary[trimmed][language]) {
      return phraseDictionary[trimmed][language];
    }

    // Check translations map
    const langDict = translations[language];
    if (langDict && langDict[trimmed]) {
      return langDict[trimmed];
    }

    return text;
  };

  const currentLangMeta = LANGUAGES.find(l => l.code === language) || LANGUAGES[0];

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, tr, currentLangMeta, LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
