'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const LANGUAGES = [
  { code: 'en', label: 'English', native: 'English', flag: '🇬🇧' },
  { code: 'hi', label: 'Hindi', native: 'हिन्दी', flag: '🇮🇳' },
  { code: 'gu', label: 'Gujarati', native: 'ગુજરાતી', flag: '🇮🇳' },
  { code: 'pa', label: 'Punjabi', native: 'ਪੰਜਾਬੀ', flag: '🇮🇳' },
  { code: 'mr', label: 'Marathi', native: 'मराठी', flag: '🇮🇳' },
  { code: 'te', label: 'Telugu', native: 'తెలుగు', flag: '🇮🇳' }
];

const phraseDictionary = {
  'Pure Spices & Masale': {
    hi: 'शुद्ध मसाले व खाद्य उत्पाद',
    gu: 'શુદ્ધ મસાલા અને ખાદ્ય ઉત્પાદનો',
    pa: 'ਸ਼ੁੱਧ ਮਸਾਲੇ ਅਤੇ ਖਾਣ-ਪੀਣ',
    mr: 'शुद्ध मसाले आणि खाद्य उत्पादने',
    te: 'స్వచ్ఛమైన మసాలాలు & ఆహార ఉత్పత్తులు'
  },
  'Electronics & Smart Tech': {
    hi: 'इलेक्ट्रॉनिक्स व स्मार्ट गैजेट्स',
    gu: 'ઇલેક્ટ્રોનિક્સ અને સ્માર્ટ ગેજેટ્સ',
    pa: 'ਇਲੈਕਟ੍ਰਾਨਿਕਸ ਅਤੇ ਸਮਾਰਟ ਗੈਜੇਟਸ',
    mr: 'इलेक्ट्रॉनिक्स आणि स्मार्ट गॅजेट्स',
    te: 'ఎలక్ట్రానిక్స్ & స్మార్ట్ గాడ్జెట్లు'
  },
  'Home Decor & Living': {
    hi: 'होम डेकोर व आधुनिक साज-सज्जा',
    gu: 'હોમ ડેકોર અને આધુનિક સજાવટ',
    pa: 'ਹੋਮ ਡੇਕੋਰ ਅਤੇ ਆਧੁਨਿਕ ਸਜਾਵਟ',
    mr: 'होम डेकोर आणि आधुनिक सजावट',
    te: 'హోమ్ డెకర్ & ఆధునిక అలంకరణ'
  },
  'Kitchen & Home Appliances': {
    hi: 'किचन व घरेलू उपकरण',
    gu: 'કિચન અને ઘરગથ્થુ ઉપકરણો',
    pa: 'ਕਿਚਨ ਅਤੇ ਘਰੇਲੂ ਉਪਕਰਨ',
    mr: 'किचन आणि घरगुती उपकरणे',
    te: 'వంటగది & గృహోపకరణాలు'
  },
  'Hardware & Power Tools': {
    hi: 'हार्डवेयर व पावर टूल्स',
    gu: 'હાર્ડવેર અને પાવર ટૂલ્સ',
    pa: 'ਹਾਰਡਵੇਅਰ ਅਤੇ ਪਾਵਰ ਟੂਲਜ਼',
    mr: 'हार्डवेअर आणि पॉवर टूल्स',
    te: 'హార్డ్‌వేర్ & పవర్ టూల్స్'
  },
  'Organic Groceries & Oils': {
    hi: 'ऑर्गेनिक किराना व शुद्ध तेल',
    gu: 'ઓર્ગેનિક કરિયાણું અને શુદ્ધ તેલ',
    pa: 'ਔਰਗੈਨਿਕ ਰਾਸ਼ਨ ਅਤੇ ਸ਼ੁੱਧ ਤੇਲ',
    mr: 'सेंद्रिय किराणा आणि शुद्ध तेल',
    te: 'సేంద్రీయ కిరాణా & స్వచ్ఛమైన నూనెలు'
  },
  'All Products Catalog': {
    hi: 'सभी उत्पाद कैटलॉग',
    gu: 'બધા ઉત્પાદનો કેટેલોગ',
    pa: 'ਸਾਰੇ ਉਤਪਾਦ ਕੈਟਾਲਾਗ',
    mr: 'सर्व उत्पादने कॅटलॉग',
    te: 'అన్ని ఉత్పత్తుల కేటలాగ్'
  },
  '0% No-Cost EMI Available': {
    hi: '0% नो-कॉस्ट ईएमआई उपलब्ध',
    gu: '0% સરળ ઈએમઆઈ ઉપલબ્ધ',
    pa: '0% ਆਸਾਨ ਕਿਸ਼ਤਾਂ ਉਪਲਬਧ',
    mr: '0% नो-कॉस्ट ईएमआय उपलब्ध',
    te: '0% సులభ EMI అందుబాటులో ఉంది'
  }
};

const translations = {
  en: {
    home: 'Home',
    all_products: 'All Products',
    categories: 'Categories',
    search_placeholder: 'Search spices, electronics, home decor, appliances, tools...',
    search: 'Search',
    account: 'My Account',
    my_profile: 'My Profile',
    my_orders: 'My Orders & Invoices',
    saved_wishlist: 'Saved Wishlist',
    support_messages: 'Support Messages',
    login: 'Customer Sign In',
    logout: 'Sign Out',
    cart: 'Cart',
    helpline: '+91 63952 11953',
    customer_desk: 'Customer Priority Desk',
    free_delivery_alert: 'Free Express Doorstep Delivery on orders above ₹499',
    add_to_cart: 'Add to Cart',
    buy_now: 'Buy Now',
    sold_out: 'Sold Out',
    in_stock: '✓ In Stock - Ready for Express Dispatch',
    low_stock: '⚡ Only Few Units Left',
    out_of_stock: 'Currently Out of Stock',
    verified_reviews: '100% Verified Buyer Reviews',
    emi_starting: 'EASY 0% NO-COST EMI AVAILABLE',
    view_emi_plans: 'View EMI Plans',
    ask_specialist: 'Ask Shopping AI Assistant',
    whatsapp_advisor: 'WhatsApp Shopping Assistant',
    share_product: 'Share Product',
    share: 'Share',
    model: 'Model',
    sku: 'SKU',
    save: 'Save',
    extra_discount: 'Special Deal',
    incl_gst: 'Inclusive of all taxes & GST',
    overview_title: 'Product Overview & Specifications',
    specifications_title: 'Technical Specifications',
    key_features: 'Key Features & Benefits',
    whats_in_box: "What's in the Box",
    faq_title: 'Frequently Asked Questions (FAQ)',
    warranty: 'Official Brand Warranty',
    free_delivery: 'Free Pan-India Delivery',
    shopping_cart: 'Shopping Cart',
    cart_empty: 'Your shopping cart is empty',
    browse_catalog: 'Explore All Categories',
    order_summary: 'Order Summary',
    subtotal: 'Item Subtotal',
    estimated_gst: 'GST Tax (Included)',
    delivery_charge: 'Delivery Charges',
    proceed_to_checkout: 'Proceed to Checkout',
    checkout_title: 'Checkout & Delivery Confirmation',
    step1_auth: 'Step 1: Sign In Required to Confirm Order',
    existing_login: 'Customer Sign In',
    new_registration: 'New Customer Registration',
    delivery_address: 'Shipping & Delivery Address',
    payment_mode: 'Select Payment Mode',
    confirm_order: 'Confirm & Place Order',
    all_products_catalog: 'All Products Catalog',
    spices_masale: 'Pure Spices & Masale',
    electronics: 'Electronics & Smart Tech',
    home_decor: 'Home Decor & Living',
    helpline_faqs: 'Helpline & FAQs',
    pan_india_delivery: 'Pan-India Express Delivery',
    today_deals: "Today's Super Deals",
    combo_save: 'Combo Savings',
    add_all_to_cart: 'Add All to Cart',
    frequently_bought_together: 'Frequently Bought Together',
    claimed: 'Claimed',
    claim_deal_now: 'Claim Deal Now'
  },
  hi: {
    home: 'होम',
    all_products: 'सभी उत्पाद',
    categories: 'कैटेगरी',
    search_placeholder: 'मसाले, इलेक्ट्रॉनिक्स, होम डेकोर, उपकरण खोजें...',
    search: 'खोजें',
    account: 'मेरा खाता',
    my_profile: 'मेरी प्रोफाइल',
    my_orders: 'मेरे ऑर्डर्स और बिल',
    saved_wishlist: 'मेरी विशलिस्ट',
    support_messages: 'सपोर्ट मैसेजेस',
    login: 'ग्राहक लॉगिन',
    logout: 'लॉगआउट',
    cart: 'कार्ट',
    helpline: '+91 63952 11953',
    customer_desk: 'कस्टमर प्रायोरिटी डेस्क',
    free_delivery_alert: '₹499 से अधिक के ऑर्डर पर पूरे भारत में फ्री डिलीवरी',
    add_to_cart: 'कार्ट में जोड़ें',
    buy_now: 'अभी खरीदें',
    sold_out: 'स्टॉक समाप्त',
    in_stock: '✓ स्टॉक में उपलब्ध - तुरंत डिस्पैच',
    low_stock: '⚡ सीमित स्टॉक बचा है',
    out_of_stock: 'वर्तमान में अनुपलब्ध',
    verified_reviews: '100% सत्यापित खरीदार समीक्षाएं',
    emi_starting: 'आसान 0% नो-कॉस्ट ईएमआई उपलब्ध',
    view_emi_plans: 'ईएमआई प्लान देखें',
    ask_specialist: 'शॉपिंग AI असिस्टेंट से पूछें',
    whatsapp_advisor: 'व्हाट्सएप सहायक',
    share_product: 'शेयर करें',
    share: 'शेयर',
    model: 'मॉडल',
    sku: 'एसकेयू',
    save: 'बचत',
    extra_discount: 'विशेष छूट',
    incl_gst: 'जीएसटी और सभी टैक्स सहित',
    overview_title: 'उत्पाद विवरण व विशेषताएं',
    specifications_title: 'तकनीकी विवरण',
    key_features: 'मुख्य विशेषताएं',
    whats_in_box: 'बॉक्स में क्या मिलेगा',
    faq_title: 'सामान्य प्रश्न (FAQ)',
    warranty: 'आधिकारिक ब्रांड वारंटी',
    free_delivery: 'फ्री सुरक्षित डिलीवरी',
    shopping_cart: 'शॉपिंग कार्ट',
    cart_empty: 'आपकी कार्ट खाली है',
    browse_catalog: 'कैटलॉग देखें',
    order_summary: 'ऑर्डर सारांश',
    subtotal: 'कुल राशि',
    estimated_gst: 'जीएसटी (समाहित)',
    delivery_charge: 'डिलीवरी शुल्क',
    proceed_to_checkout: 'चेकआउट करें',
    checkout_title: 'ऑर्डर व डिलीवरी पुष्टि',
    step1_auth: 'स्टेप 1: ऑर्डर के लिए लॉगिन आवश्यक है',
    existing_login: 'ग्राहक लॉगिन',
    new_registration: 'नया ग्राहक पंजीकरण',
    delivery_address: 'डिलीवरी का पता',
    payment_mode: 'भुगतान विकल्प चुनें',
    confirm_order: 'ऑर्डर कन्फर्म करें',
    all_products_catalog: 'सभी उत्पाद कैटलॉग',
    spices_masale: 'शुद्ध मसाले व खाद्य उत्पाद',
    electronics: 'इलेक्ट्रॉनिक्स व गैजेट्स',
    home_decor: 'होम डेकोर व सजावट',
    helpline_faqs: 'हेल्पलाइन व प्रश्न',
    pan_india_delivery: 'अखिल भारतीय सुपरफास्ट डिलीवरी',
    today_deals: 'आज के महा ऑफर्स',
    combo_save: 'कॉम्बो बचत',
    add_all_to_cart: 'सभी को कार्ट में जोड़ें',
    frequently_bought_together: 'अक्सर एक साथ खरीदे जाने वाले उत्पाद',
    claimed: 'बुक हो चुका',
    claim_deal_now: 'ऑफर पाएं'
  },
  gu: {
    home: 'મુખ્ય પૃષ્ઠ',
    all_products: 'બધા ઉત્પાદનો',
    categories: 'કેટેગરીઝ',
    search_placeholder: 'મસાલા, ઈલેક્ટ્રોનિક્સ, હોમ ડેકોર, ઉપકરણો શોધો...',
    search: 'શોધો',
    account: 'મારું ખાતું',
    my_profile: 'મારી પ્રોફાઇલ',
    my_orders: 'મારા ઓર્ડર અને બિલ',
    saved_wishlist: 'મનપસંદ યાદી',
    support_messages: 'સહાયતા મેસેજ',
    login: 'ગ્રાહક લૉગિન',
    logout: 'લૉગઆઉટ',
    cart: 'કાર્ટ',
    helpline: '+91 63952 11953',
    customer_desk: 'ગ્રાહક પ્રાયોરિટી ડેસ્ક',
    free_delivery_alert: '₹499 થી વધુના ઓર્ડર પર ફ્રી હોમ ડિલિવરી',
    add_to_cart: 'કાર્ટમાં ઉમેરો',
    buy_now: 'હમણાં ખરીદો',
    sold_out: 'સ્ટોક ખલાસ',
    in_stock: '✓ સ્ટોકમાં ઉપલબ્ધ - તુરંત ડિસ્પેચ',
    low_stock: '⚡ મર્યાદિત સ્ટોક',
    out_of_stock: 'સ્ટોક ખલાસ',
    verified_reviews: '100% ચકાસાયેલ ગ્રાહક રિવ્યુ',
    emi_starting: 'સરળ 0% નો-કોસ્ટ ઈએમઆઈ',
    view_emi_plans: 'ઈએમઆઈ પ્લાન જુઓ',
    ask_specialist: 'શોપિંગ AI સહાયકને પૂછો',
    whatsapp_advisor: 'વોટ્સએપ સહાયક',
    share_product: 'શેર કરો',
    share: 'શેર',
    model: 'મોડલ',
    sku: 'એસકેયુ',
    save: 'બચત',
    extra_discount: 'વિશેષ ઓફર',
    incl_gst: 'જીએસટી સહિત',
    overview_title: 'પ્રોડક્ટ માહિતી અને કાર્યક્ષમતા',
    specifications_title: 'ટેકનિકલ વિગતો',
    key_features: 'મુખ્ય વિશેષતાઓ',
    whats_in_box: 'બોક્સમાં શું મળશે',
    faq_title: 'સામાન્ય પ્રશ્નો',
    warranty: 'કંપની વોરંટી',
    free_delivery: 'ફ્રી ડિલિવરી',
    shopping_cart: 'શોપિંગ કાર્ટ',
    cart_empty: 'તમારી કાર્ટ ખાલી છે',
    browse_catalog: 'કેટેલોગ જુઓ',
    order_summary: 'ઓર્ડર સારાંશ',
    subtotal: 'કુલ રકમ',
    estimated_gst: 'અંદાજિત જીએસટી (સમાવિષ્ટ)',
    delivery_charge: 'ડિલિવરી ચાર્જ',
    proceed_to_checkout: 'ચેકઆઉટ કરો',
    checkout_title: 'ઓર્ડર અને ડિલિવરી કન્ફર્મેશન',
    step1_auth: 'સ્ટેપ 1: ઓર્ડર માટે લૉગિન જરૂરી છે',
    existing_login: 'ગ્રાહક લૉગિન',
    new_registration: 'નવા ગ્રાહક રજીસ્ટ્રેશન',
    delivery_address: 'ડિલિવરી સરનામું',
    payment_mode: 'પેમેન્ટ પદ્ધતિ પસંદ કરો',
    confirm_order: 'ઓર્ડર કન્ફર્મ કરો',
    all_products_catalog: 'બધા ઉત્પાદનો કેટેલોગ',
    spices_masale: 'શુદ્ધ મસાલા અને ખાદ્ય ઉત્પાદનો',
    electronics: 'ઈલેક્ટ્રોનિક્સ અને ગેજેટ્સ',
    home_decor: 'હોમ ડેકોર અને સજાવટ',
    helpline_faqs: 'હેલ્પલાઇન અને પ્રશ્નો',
    pan_india_delivery: 'ઓલ ઈન્ડિયા ફાસ્ટ ડિલિવરી',
    today_deals: 'આજના સુપર ઑફર્સ',
    combo_save: 'કોમ્બો બચત',
    add_all_to_cart: 'બધું કાર્ટમાં ઉમેરો',
    frequently_bought_together: 'વારંવાર સાથે ખરીદાતા ઉત્પાદનો',
    claimed: 'બુક થયું',
    claim_deal_now: 'ઑફર મેળવો'
  },
  pa: {
    home: 'ਹੋਮ',
    all_products: 'ਸਾਰੇ ਉਤਪਾਦ',
    categories: 'ਕੈਟਾਗਰੀਆਂ',
    search_placeholder: 'ਮਸਾਲੇ, ਇਲੈਕਟ੍ਰਾਨਿਕਸ, ਹੋਮ ਡੇਕੋਰ, ਉਪਕਰਨ ਲੱਭੋ...',
    search: 'ਖੋਜੋ',
    account: 'ਮੇਰਾ ਖਾਤਾ',
    my_profile: 'ਮੇਰੀ ਪ੍ਰੋਫਾਈਲ',
    my_orders: 'ਮੇਰੇ ਆਰਡਰ ਤੇ ਬਿੱਲ',
    saved_wishlist: 'ਪਸੰਦੀਦਾ ਸੂਚੀ',
    support_messages: 'ਸਹਾਇਤਾ ਸੁਨੇਹੇ',
    login: 'ਗਾਹਕ ਲਾਗਇਨ',
    logout: 'ਲਾਗਆਉਟ',
    cart: 'ਕਾਰਟ',
    helpline: '+91 63952 11953',
    customer_desk: 'ਗਾਹਕ ਪ੍ਰਾਥਮਿਕਤਾ ਡੈਸਕ',
    free_delivery_alert: '₹499 ਤੋਂ ਵੱਧ ਦੇ ਆਰਡਰਾਂ ਉੱਤੇ ਮੁਫ਼ਤ ਹੋਮ ਡਿਲਿਵਰੀ',
    add_to_cart: 'ਕਾਰਟ ਵਿੱਚ ਪਾਓ',
    buy_now: 'ਹੁਣੇ ਖਰੀਦੋ',
    sold_out: 'ਸਟਾਕ ਖਤਮ',
    in_stock: '✓ ਸਟਾਕ ਵਿੱਚ ਉਪਲਬਧ - ਤੁਰੰਤ ਡਿਸਪੈਚ',
    low_stock: '⚡ ਸੀਮਤ ਸਟਾਕ',
    out_of_stock: 'ਸਟਾਕ ਖਤਮ',
    verified_reviews: '100% ਪ੍ਰਮਾਣਿਤ ਗਾਹਕ ਸਮੀਖਿਆਵਾਂ',
    emi_starting: 'ਆਸਾਨ 0% ਨੋ-ਕਾਸਟ ਕਿਸ਼ਤਾਂ',
    view_emi_plans: 'ਕਿਸ਼ਤ ਪਲਾਨ ਦੇਖੋ',
    ask_specialist: 'ਸ਼ਾਪਿੰਗ AI ਅਸਿਸਟੈਂਟ ਨੂੰ ਪੁੱਛੋ',
    whatsapp_advisor: 'ਵਟਸਐਪ ਸਹਾਇਕ',
    share_product: 'ਸ਼ੇਅਰ ਕਰੋ',
    share: 'ਸ਼ੇਅਰ',
    model: 'ਮਾਡਲ',
    sku: 'ਐਸ.ਕੇ.ਯੂ',
    save: 'ਬੱਚਤ',
    extra_discount: 'ਵਿਸ਼ੇਸ਼ ਛੋਟ',
    incl_gst: 'ਜੀ.ਐਸ.ਟੀ ਸਮੇਤ',
    overview_title: 'ਉਤਪਾਦ ਜਾਣਕਾਰੀ',
    specifications_title: 'ਤਕਨੀਕੀ ਵੇਰਵੇ',
    key_features: 'ਮੁੱਖ ਵਿਸ਼ੇਸ਼ਤਾਵਾਂ',
    whats_in_box: 'ਬਾਕਸ ਵਿੱਚ ਕੀ ਹੈ',
    faq_title: 'ਆਮ ਪੁੱਛੇ ਜਾਂਦੇ ਸਵਾਲ',
    warranty: 'ਅਧਿਕਾਰਤ ਬ੍ਰਾਂਡ ਵਾਰੰਟੀ',
    free_delivery: 'ਮੁਫ਼ਤ ਡਿਲਿਵਰੀ',
    shopping_cart: 'ਖਰੀਦਦਾਰੀ ਕਾਰਟ',
    cart_empty: 'ਤੁਹਾਡੀ ਕਾਰਟ ਖਾਲੀ ਹੈ',
    browse_catalog: 'ਕੈਟਾਲਾਗ ਦੇਖੋ',
    order_summary: 'ਆਰਡਰ ਸਾਰ',
    subtotal: 'ਕੁੱਲ ਰਕਮ',
    estimated_gst: 'ਅੰਦਾਜ਼ਨ ਜੀ.ਐਸ.ਟੀ',
    delivery_charge: 'ਡਿਲਿਵਰੀ ਖਰਚਾ',
    proceed_to_checkout: 'ਚੈੱਕਆਉਟ ਕਰੋ',
    checkout_title: 'ਆਰਡਰ ਅਤੇ ਡਿਲਿਵਰੀ ਪੁਸ਼ਟੀ',
    step1_auth: 'ਕਦਮ 1: ਆਰਡਰ ਲਈ ਲਾਗਇਨ ਲਾਜ਼ਮੀ ਹੈ',
    existing_login: 'ਗਾਹਕ ਲਾਗਇਨ',
    new_registration: 'ਨਵਾਂ ਗਾਹਕ ਰਜਿਸਟ੍ਰੇਸ਼ਨ',
    delivery_address: 'ਡਿਲਿਵਰੀ ਦਾ ਪਤਾ',
    payment_mode: 'ਭੁਗਤਾਨ ਵਿਕਲਪ ਚੁਣੋ',
    confirm_order: 'ਆਰਡਰ ਪੱਕਾ ਕਰੋ',
    all_products_catalog: 'ਸਾਰੇ ਉਤਪਾਦ ਕੈਟਾਲਾਗ',
    spices_masale: 'ਸ਼ੁੱਧ ਮਸਾਲੇ ਅਤੇ ਖਾਣ-ਪੀਣ',
    electronics: 'ਇਲੈਕਟ੍ਰਾਨਿਕਸ ਅਤੇ ਗੈਜੇਟਸ',
    home_decor: 'ਹੋਮ ਡੇਕੋਰ ਤੇ ਸਜਾਵਟ',
    helpline_faqs: 'ਹੈਲਪਲਾਈਨ ਤੇ ਸਵਾਲ',
    pan_india_delivery: 'ਪੂਰੇ ਭਾਰਤ ਵਿੱਚ ਤੇਜ਼ ਡਿਲਿਵਰੀ',
    today_deals: 'ਅੱਜ ਦੇ ਸੁਪਰ ਆਫਰਜ਼',
    combo_save: 'ਕਾਂਬੋ ਬੱਚਤ',
    add_all_to_cart: 'ਸਾਰੇ ਕਾਰਟ ਵਿੱਚ ਸ਼ਾਮਲ ਕਰੋ',
    frequently_bought_together: 'ਅਕਸਰ ਇਕੱਠੇ ਖਰੀਦੇ ਜਾਣ ਵਾਲੇ ਉਤਪਾਦ',
    claimed: 'ਬੁੱਕ ਕੀਤਾ',
    claim_deal_now: 'ਆਫਰ ਪ੍ਰਾਪਤ ਕਰੋ'
  },
  mr: {
    home: 'मुख्य पृष्ठ',
    all_products: 'सर्व उत्पादने',
    categories: 'वर्गवारी',
    search_placeholder: 'मसाले, इलेक्ट्रॉनिक्स, होम डेकोर, उपकरणे शोधा...',
    search: 'शोधा',
    account: 'माझे खाते',
    my_profile: 'माझी प्रोफाइल',
    my_orders: 'माझ्या ऑर्डर्स आणि बिले',
    saved_wishlist: 'आवडती यादी',
    support_messages: 'सपोर्ट मेसेज',
    login: 'ग्राहक लॉगिन',
    logout: 'लॉगआउट',
    cart: 'कार्ट',
    helpline: '+91 63952 11953',
    customer_desk: 'ग्राहक प्राधान्य सेवा',
    free_delivery_alert: '₹499 वरील सर्व ऑर्डर्सवर मोफत डिलिव्हरी',
    add_to_cart: 'कार्टमध्ये जोडा',
    buy_now: 'आता खरेदी करा',
    sold_out: 'स्टॉक संपला',
    in_stock: '✓ स्टॉकमध्ये उपलब्ध - त्वरित पाठवले जाईल',
    low_stock: '⚡ मर्यादित स्टॉक शिल्लक',
    out_of_stock: 'सध्या उपलब्ध नाही',
    verified_reviews: '100% पडताळणी केलेले ग्राहक परीक्षण',
    emi_starting: 'सोपे 0% नो-कॉस्ट ईएमआय',
    view_emi_plans: 'ईएमआय प्लॅन पहा',
    ask_specialist: 'शॉपिंग AI सहाय्यकाला विचारा',
    whatsapp_advisor: 'व्हॉट्सॲप सहाय्यक',
    share_product: 'शेअर करा',
    share: 'शेअर',
    model: 'मॉडेल',
    sku: 'एसकेयू',
    save: 'बचत',
    extra_discount: 'विशेष सवलत',
    incl_gst: 'सर्व कर व जीएसटी समाविष्ट',
    overview_title: 'उत्पादन माहिती व वैशिष्ट्ये',
    specifications_title: 'तांत्रिक तपशील',
    key_features: 'प्रमुख वैशिष्ट्ये',
    whats_in_box: 'बॉक्समध्ये काय मिळेल',
    faq_title: 'नेहमी विचारले जाणारे प्रश्न (FAQ)',
    warranty: 'कंपनी वॉरंटी',
    free_delivery: 'मोफत सुरक्षित डिलिव्हरी',
    shopping_cart: 'शॉपिंग कार्ट',
    cart_empty: 'तुमची कार्ट रिकामी आहे',
    browse_catalog: 'कॅटलॉग एक्सप्लोर करा',
    order_summary: 'ऑर्डर सारांश',
    subtotal: 'एकूण रक्कम',
    estimated_gst: 'अंदाजे जीएसटी (समाविष्ट)',
    delivery_charge: 'डिलिव्हरी शुल्क',
    proceed_to_checkout: 'चेकआऊट करा',
    checkout_title: 'ऑर्डर आणि डिलिव्हरी निश्चिती',
    step1_auth: 'पायरी 1: ऑर्डरसाठी लॉगिन आवश्यक आहे',
    existing_login: 'ग्राहक लॉगिन',
    new_registration: 'नवीन ग्राहक नोंदणी',
    delivery_address: 'डिलिव्हरी पत्ता',
    payment_mode: 'पेमेंट पद्धत निवडा',
    confirm_order: 'ऑर्डर निश्चित करा',
    all_products_catalog: 'सर्व उत्पादने कॅटलॉग',
    spices_masale: 'शुद्ध मसाले व खाद्य उत्पादने',
    electronics: 'इलेक्ट्रॉनिक्स आणि गॅजेट्स',
    home_decor: 'होम डेकोर आणि सजावट',
    helpline_faqs: 'हेल्पलाइन व प्रश्न',
    pan_india_delivery: 'संपूर्ण भारतात जलद डिलिव्हरी',
    today_deals: 'आजच्या सुपर डील्स',
    combo_save: 'कॉम्बो बचत',
    add_all_to_cart: 'सर्व कार्टमध्ये जोडा',
    frequently_bought_together: 'नेहमी एकत्र खरेदी केली जाणारी उत्पादने',
    claimed: 'बुक झाले',
    claim_deal_now: 'ऑफर मिळवा'
  },
  te: {
    home: 'హోమ్',
    all_products: 'అన్ని ఉత్పత్తులు',
    categories: 'వర్గాలు',
    search_placeholder: 'మసాలాలు, ఎలక్ట్రానిక్స్, హోమ్ డెకర్, ఉపకరణాలు శోధించండి...',
    search: 'శోధించండి',
    account: 'నా ఖాతా',
    my_profile: 'నా ప్రొఫైల్',
    my_orders: 'నా ఆర్డర్లు & బిల్లులు',
    saved_wishlist: 'సేవ్ చేసిన విష్‌లిస్ట్',
    support_messages: 'సపోర్ట్ సందేశాలు',
    login: 'కస్టమర్ లాగిన్',
    logout: 'లాగౌట్',
    cart: 'కార్ట్',
    helpline: '+91 63952 11953',
    customer_desk: 'కస్టమర్ ప్రయారిటీ డెస్క్',
    free_delivery_alert: '₹499 కంటే ఎక్కువ ఆర్డర్‌లపై ఉచిత డెలివరీ',
    add_to_cart: 'కార్ట్‌కు జోడించండి',
    buy_now: 'ఇప్పుడే కొనండి',
    sold_out: 'స్టాక్ ముగిసింది',
    in_stock: '✓ స్టాక్‌లో అందుబాటులో ఉంది',
    low_stock: '⚡ పరిమిత స్టాక్ మాత్రమే ఉంది',
    out_of_stock: 'ప్రస్తుతం అందుబాటులో లేదు',
    verified_reviews: '100% ధృవీకరించబడిన కస్టమర్ సమీక్షలు',
    emi_starting: 'సులభమైన 0% నో-కాస్ట్ EMI',
    view_emi_plans: 'EMI ప్లాన్‌లను చూడండి',
    ask_specialist: 'షాపింగ్ AI అసిస్టెంట్‌ని అడగండి',
    whatsapp_advisor: 'వాట్సాప్ అసిస్టెంట్',
    share_product: 'షేర్ చేయండి',
    share: 'షేర్',
    model: 'మోడల్',
    sku: 'SKU',
    save: 'ఆదా',
    extra_discount: 'ప్రత్యేక తగ్గింపు',
    incl_gst: 'అన్ని పన్నులు & జీఎస్టీతో కలిపి',
    overview_title: 'ఉత్పత్తి సమాచారం & లక్షణాలు',
    specifications_title: 'సాంకేతిక వివరాలు',
    key_features: 'ప్రధాన ఫీచర్లు',
    whats_in_box: 'బాక్స్‌లో ఏముంది',
    faq_title: 'తరచుగా అడిగే ప్రశ్నలు (FAQ)',
    warranty: 'అధికారిక బ్రాండ్ వారంటీ',
    free_delivery: 'ఉచిత డెలివరీ',
    shopping_cart: 'షాపింగ్ కార్ట్',
    cart_empty: 'మీ కార్ట్ ఖాళీగా ఉంది',
    browse_catalog: 'కేటలాగ్ చూడండి',
    order_summary: 'ఆర్డర్ సారాంశం',
    subtotal: 'మొత్తం ధర',
    estimated_gst: 'జీఎస్టీ (కలిపి)',
    delivery_charge: 'డెలివరీ ఛార్జీలు',
    proceed_to_checkout: 'చెక్‌అవుట్‌కు వెళ్లండి',
    checkout_title: 'ఆర్డర్ మరియు డెలివరీ నిర్ధారణ',
    step1_auth: 'దశ 1: ఆర్డర్ కోసం లాగిన్ అవసరం',
    existing_login: 'కస్టమర్ లాగిన్',
    new_registration: 'కొత్త కస్టమర్ రిజిస్ట్రేషన్',
    delivery_address: 'డెలివరీ చిరునామా',
    payment_mode: 'చెల్లింపు పద్ధతి ఎంచుకోండి',
    confirm_order: 'ఆర్డర్‌ని నిర్ధారించండి',
    all_products_catalog: 'అన్ని ఉత్పత్తుల కేటలాగ్',
    spices_masale: 'స్వచ్ఛమైన మసాలాలు & ఆహార ఉత్పత్తులు',
    electronics: 'ఎలక్ట్రానిక్స్ & గాడ్జెట్లు',
    home_decor: 'హోమ్ డెకర్ & అలంకరణ',
    helpline_faqs: 'హెల్ప్‌లైన్ & ప్రశ్నలు',
    pan_india_delivery: 'భారతదేశం అంతటా వేగవంతమైన డెలివరీ',
    today_deals: 'నేటి సూపర్ ఆఫర్లు',
    combo_save: 'కాంబో ఆదా',
    add_all_to_cart: 'అన్నీ కార్ట్‌కు జోడించండి',
    frequently_bought_together: 'తరచుగా కలిసి కొనుగోలు చేసే ఉత్పత్తులు',
    claimed: 'బుక్ చేయబడింది',
    claim_deal_now: 'ఆఫర్ పొందండి'
  }
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    if (typeof window === 'undefined') return 'en';
    try {
      const saved = localStorage.getItem('eidula_lang') || localStorage.getItem('siddhiva_lang');
      if (saved && translations[saved]) {
        return saved;
      }
      return 'en';
    } catch {
      return 'en';
    }
  });

  useEffect(() => {
    try {
      localStorage.setItem('eidula_lang', language);
    } catch {}
  }, [language]);

  const t = (key, fallback = '') => {
    const langDict = translations[language] || translations.en;
    if (langDict && langDict[key]) return langDict[key];
    if (translations.en && translations.en[key]) return translations.en[key];
    return fallback || key;
  };

  /**
   * Translate dynamic phrase or title
   */
  const tr = (text) => {
    if (!text || typeof text !== 'string') return text;
    if (language === 'en') return text;

    const trimmed = text.trim();

    if (phraseDictionary[trimmed] && phraseDictionary[trimmed][language]) {
      return phraseDictionary[trimmed][language];
    }

    const langDict = translations[language];
    if (langDict && langDict[trimmed]) {
      return langDict[trimmed];
    }

    return text;
  };

  const currentLangMeta = LANGUAGES.find(l => l.code === language) || LANGUAGES[0];

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, tr, currentLangMeta, LANGUAGES }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
